academic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('projects/index')),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls')),
]

projects/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import UpdateView

from django.contrib.auth import views
from projects.filters import ThesisInfoFilter, MeetingInfoFilter, NoticeFilter
from projects.form import ThesisInfoAddForm, MeetingInfoAddForm, NoticeAddForm
from .models import ThesisInfo, MeetingInfo,Notice
from .views import *

app_name = 'projects'

urlpatterns = [
    url(r'^login/$', login,
        {'template_name': 'projects/myuser/login.html'},name='userLogin'),
    url(r'^logout/$', views.logout, {'template_name': 'projects/myuser/login.html'}, name='logout'),

    url(r'^index$', indexView, name='index'),

    #thesisInfo
    url(r'^thesisInfoList$',
        ThesisInfoListView.as_view(model=ThesisInfo, filterset_class=ThesisInfoFilter, template_name='projects/thesisInfo/list.html',
                                 paginate_by=7),name='thesisInfoList'),
    url(r'^thesisInfoAdd$',add, name='thesisInfoAdd'),
    url(r'^thesisInfo/(?P<pk>[0-9]+)/$', DetailView.as_view(model=ThesisInfo, template_name='projects/thesisInfo/detail.html'),
        name='thesisInfoDetail'),
    url(r'^(?P<pk>[0-9]+)/updatethesisInfo$', UpdateView.as_view(model=ThesisInfo, form_class=ThesisInfoAddForm,
                                                                 template_name='projects/thesisInfo/update.html',
                                                                 success_url=reverse_lazy('projects:thesisInfoList')),
        name='thesisInfoUpdate'),
    url(r'^(?P<pk>[0-9]+)/updatethesisInfo$', UpdateView.as_view(model=ThesisInfo, form_class=ThesisInfoAddForm,
                                                                 template_name='projects/thesisInfo/update.html',
                                                                 success_url=reverse_lazy('projects:thesisInfoList')),
        name='thesisInfoReview'),
    url(r'^(?P<pk>[0-9]+)/updatethesisInfo$', UpdateView.as_view(model=ThesisInfo, form_class=ThesisInfoAddForm,
                                                                 template_name='projects/thesisInfo/update.html',
                                                                 success_url=reverse_lazy('projects:thesisInfoList')),
        name='thesisInfoCheck'),
    url(r'^(?P<pk>[0-9]+)/deletethesisInfo$',
        DeleteView.as_view(model=ThesisInfo, success_url=reverse_lazy('projects:thesisInfoList')), name='thesisInfoDelete'),
    #meetingInfo
    url(r'^meetingInfoList$',
        MeetingInfoListView.as_view(model=MeetingInfo, filterset_class=MeetingInfoFilter,
                                   template_name='projects/meetingInfo/list.html',
                                   paginate_by=7), name='meetingInfoList'),
    url(r'^meetingInfoAdd$',
        CreateView.as_view(model=MeetingInfo, template_name='projects/meetingInfo/add.html',
                           form_class=MeetingInfoAddForm,
                           success_url=reverse_lazy('projects:meetingInfoList')), name='meetingInfoAdd'),
    url(r'^meetingInfo/(?P<pk>[0-9]+)/$',
        DetailView.as_view(model=MeetingInfo, template_name='projects/meetingInfo/detail.html'),
        name='meetingInfoDetail'),
    url(r'^(?P<pk>[0-9]+)/updatemeetingInfo$', UpdateView.as_view(model=MeetingInfo, form_class=MeetingInfoAddForm,
                                                                 template_name='projects/meetingInfo/update.html',
                                                                 success_url=reverse_lazy('projects:meetingInfoList')),
        name='meetingInfoUpdate'),
    url(r'^(?P<pk>[0-9]+)/deletemeetingInfo$',
        DeleteView.as_view(model=MeetingInfo, success_url=reverse_lazy('projects:meetingInfoList')),
        name='meetingInfoDelete'),
    #notice
    url(r'^noticeList$',
        NoticeListView.as_view(model=Notice, filterset_class= NoticeFilter,
                                   template_name='projects/notice/list.html',
                                   paginate_by=7), name='noticeList'),
    url(r'^noticeAdd$',
        CreateView.as_view(model=Notice, template_name='projects/notice/add.html',
                           form_class=NoticeAddForm,
                           success_url=reverse_lazy('projects:noticeList')), name='noticeAdd'),
    url(r'^notice/(?P<pk>[0-9]+)/$',
        DetailView.as_view(model=Notice, template_name='projects/notice/detail.html'),
        name='meetingInfoDetail'),
    url(r'^(?P<pk>[0-9]+)/updatenotice$', UpdateView.as_view(model=Notice, form_class=NoticeAddForm,
                                                                 template_name='projects/notice/update.html',
                                                                 success_url=reverse_lazy('projects:noticeList')),
        name='noticeUpdate'),
    url(r'^(?P<pk>[0-9]+)/deletenotice$',
        DeleteView.as_view(model=Notice, success_url=reverse_lazy('projects:noticeList')),
        name='noticeDelete'),
]

projects/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class userInfo(models.Model):
    USER_TYPE = (
        (1,'管理员'),
        (2,'审稿员'),
        (3,'参会者')
    )
    type = models.IntegerField(verbose_name="用户类型",choices=USER_TYPE)
    user = models.OneToOneField(User)

class ThesisInfo(models.Model):
    STATUS = (
        (1,'通过'),
        (2,'不通过'),
    )
    theme = models.CharField(verbose_name="主题", max_length=100)
    headline = models.CharField(verbose_name="摘要", max_length=100)
    keyword = models.CharField(verbose_name="关键词", max_length=50)
    user = models.ForeignKey(User,verbose_name="用户")
    thesisUrl = models.FileField(verbose_name="论文上传", upload_to='projects/static/documents/%Y/%m/%d')
    auditStatus = models.IntegerField(verbose_name="审核状态", choices=STATUS,blank=True,null=True)
    reviewStatus = models.IntegerField(verbose_name="评审状态", choices=STATUS,blank=True,null=True)
    create_time = models.DateTimeField(verbose_name="创建时间",default='2017-4-23')
    modifyTime = models.DateTimeField(verbose_name="修改时间")

class MeetingInfo(models.Model):
    meeting_name = models.CharField(verbose_name="会议名称", max_length=100)
    start_time = models.DateTimeField(verbose_name="开始时间")
    end_time = models.DateTimeField(verbose_name="结束时间")
    meeting_address = models.CharField(verbose_name="会议地址", max_length=100)
    meeting_plan = models.CharField(verbose_name="会议安排", max_length=500)
    create_time = models.DateTimeField(verbose_name="创建时间",default='2017-4-23')
    create_user = models.ForeignKey(User,verbose_name="创建人")
    def __str__(self):
        return self.meeting_name

class Notice(models.Model):
    message = models.CharField(verbose_name="信息内容",max_length=1000)
    meetingInfo = models.ForeignKey(MeetingInfo,verbose_name="会议")
    create_time = models.DateTimeField(verbose_name="创建时间",default='2017-4-23')

projects/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django_filters.views import FilterView
from projects.form import ThesisInfoAddForm
from projects.models import ThesisInfo


@csrf_protect
@never_cache
def login(request, template_name='registration/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          extra_context=None, redirect_authenticated_user=False):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name, request.GET.get(redirect_field_name, ''))

    if redirect_authenticated_user and request.user.is_authenticated:
        #redirect_to = _get_login_redirect_url(request, redirect_to)
        if redirect_to == request.path:
            raise ValueError(
                "Redirection loop for authenticated user detected. Check that "
                "your LOGIN_REDIRECT_URL doesn't point to a login page."
            )
        return HttpResponseRedirect(redirect_to)
    elif request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():
            views.auth_login(request, form.get_user())
            return HttpResponseRedirect('/projects/index')
        else:
            form = authentication_form(request)
        current_site = get_current_site(request)

        context = {
            'form': form,
            redirect_field_name: redirect_to,
            'site': current_site,
            'site_name': current_site.name,
        }
        if extra_context is not None:
            context.update(extra_context)
        return TemplateResponse(request, template_name, context)


class ThesisInfoListView(FilterView):
    def get_queryset(self):
        if self.request.user.username == 'admin':
            query_set = ThesisInfo.objects.all()
        if self.request.user.username == 'wangkai1':
            query_set = ThesisInfo.objects.filter(user=self.request.user)
        else:
            query_set = ThesisInfo.objects.all()
        return query_set
    def get_paginate_by(self, queryset):
        return self.paginate_by

class NoticeListView(FilterView):
    def get_paginate_by(self, queryset):
        return self.paginate_by

class MeetingInfoListView(FilterView):
    def get_paginate_by(self, queryset):
        return self.paginate_by

@login_required
def indexView(request):
        return render(request, 'projects/index.html')

def add(request):
    template = 'projects/thesisInfo/add.html'
    if request.method == 'POST':
        form = ThesisInfoAddForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/projects/thesisInfoList')
    else:
        form = ThesisInfoAddForm()
    return render(request, template, {'form': form})

def upload(request):
    template = 'projects/thesisInfo/update.html'
    if request.method == 'POST':
        form = ThesisInfoAddForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/projects/thesisInfoList')
    else:
        form = ThesisInfoAddForm()
    return render(request, template, {'form': form})



        # @receiver(signals.post_init, sender=Notice)
# def project_init_signal(instance, sender, **kwargs):
#     instance.__noticeid = instance.pk
#     instance.__meetingInfo = instance.meetingInfo
#     instance.__message = instance.message
#
# @receiver(signals.post_save, sender=Notice)
# def notice_post_save(instance, created, raw, update_fields,sender, **kwargs):

projects/templates/base.html
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block headtitle %}学术会议管理系统{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.6 -->
  <link rel="stylesheet" href={% static "/css/bootstrap.min.css"%}>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" href={% static "plugins/fullcalendar/fullcalendar.min.css"%}>
  <link rel="stylesheet" href={% static "/plugins/fullcalendar/fullcalendar.print.css"%} media="print">
  <!-- Theme style -->
  <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
        page. However, you can choose any other skin. Make sure you
        apply the skin class to the body tag so the changes take effect.
  -->
  <link rel="stylesheet" href={% static "dist/css/skins/skin-blue.min.css"%}>
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <!-- jQuery 2.2.3 -->
<script src={% static "plugins/jQuery/jquery-2.2.3.min.js"%}></script>
<!-- Bootstrap 3.3.6 -->
<script src={% static "js/bootstrap.min.js"%}></script>
<!-- AdminLTE App -->
<script src={% static "dist/js/app.min.js"%}></script>
<script src={% static "js/jscookie.js" %}></script>
<script src={% static "plugins/datepicker/bootstrap-datepicker.js" %}></script>
<script src={% static "plugins/datepicker/locales/bootstrap-datepicker.zh-CN.js" %}></script>

    <link rel="stylesheet" href={% static "plugins/datepicker/datepicker3.css" %}>
  <![endif]-->
    <link rel="stylesheet" href={% static "plugins/select2/select2.min.css"%}>
    <script src={% static "plugins/select2/select2.full.min.js"%}></script>
  <link rel="stylesheet" href={% static "dist/css/AdminLTE.min.css" %}>
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <!-- Main Header -->
  <header class="main-header">

    <!-- Logo -->
    <a href="{% url 'projects:index'%}" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini">云趣</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b></b>学术会议管理系统</span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-bell-o"></i>
              <span class="label label-warning"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <!-- Inner Menu: contains the notifications -->
                <ul class="menu">
                    {% for signal_log in signal_log_list %}
                  <li>
                    <a href="#">
                      <i class="fa fa-user text-red"></i>
                    </a>
                  </li>
                    {% endfor %}
                  <!-- end notification -->
                </ul>
              </li>
              <li class="footer"><a href="#">查看消息</a></li>
            </ul>
          </li>
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              <img src={% static "dist/img/user2-160x160.jpg"%} class="user-image" alt="User Image">
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{ request.user.username }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src={% static "dist/img/user2-160x160.jpg"%} class="img-circle" alt="User Image">
                <p>
                    {% if request.user.username == 'admin' %}会议管理员{% endif %}
                    {% if request.user.username == 'wangkai' %}审稿员{% endif %}
                    {% if request.user.username == 'wangkai1' %}参会者{% endif %}
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">

                  <a href="{% url 'projects:logout'%}" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

      <!-- Sidebar Menu -->
      <ul class="sidebar-menu">
        <li class="header"></li>
        <!-- Optionally, you can add icons to the links -->
        {% url 'projects:thesisInfoList' as nav_thesisInfoList %}
        {% url 'projects:meetingInfoList' as nav_meetingInfoList%}
        {% url 'projects:noticeList' as nav_noitceList %}
        {% if request.user.username == 'admin' %}
        <li class="header">会议管理</li>
        <li class="{% ifequal request.path nav_meetingInfoList %}active{% endifequal %}">
            <a href="{{ nav_meetingInfoList }}"><i class="fa fa-group"></i> <span>会议管理</span></a>
        </li>
        <li class="{% ifequal request.path nav_noitceList %}active{% endifequal %}">
            <a href="{{ nav_noitceList }}"><i class="fa fa-group"></i> <span>通知管理</span></a>
        </li>
        <li class="header">论文管理</li>
        <li class="{% ifequal request.path nav_thesisInfoList %}active{% endifequal %}">
            <a href="{{ nav_thesisInfoList }}"><i class="fa fa-group"></i> <span>论文管理</span></a>
        </li>
        {% endif %}
        {% if request.user.username == 'wangkai' %}
        <li class="{% ifequal request.path nav_thesisInfoList %}active{% endifequal %}">
            <a href="{{ nav_thesisInfoList }}"><i class="fa fa-group"></i> <span>论文评审</span></a>
        </li>
        {% endif %}
        {% if request.user.username == 'wangkai1' %}
        <li class="{% ifequal request.path nav_meetingInfoList %}active{% endifequal %}">
            <a href="{{ nav_meetingInfoList }}"><i class="fa fa-group"></i> <span>会议管理</span></a>
        </li>
        <li class="{% ifequal request.path nav_noitceList %}active{% endifequal %}">
            <a href="{{ nav_noitceList }}"><i class="fa fa-group"></i> <span>通知管理</span></a>
        </li>
        <li class="header">论文管理</li>
        <li class="{% ifequal request.path nav_thesisInfoList %}active{% endifequal %}">
            <a href="{{ nav_thesisInfoList }}"><i class="fa fa-group"></i> <span>论文管理</span></a>
        </li>
        {% endif %}

      </ul>
      <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="overflow:hidden;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        {% block title %}{% endblock %}
        <!--<small>Optional description</small>-->
      </h1>
    </section>
    <!-- Main content -->
    <section class="content">
    {% block content %}{% endblock %}
      <!-- Your Page Content Here -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
       学术会议管理系统
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2017 <a href="#">wangkai</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                  <span class="label label-danger pull-right">70%</span>
                </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->


<!-- Optionally, you can add Slimscroll and FastClick plugins.
     Both of these plugins are recommended to enhance the
     user experience. Slimscroll is required when using the
     fixed layout. -->
</body>
</html>

projects/templates/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}
    {% block title %}
        这个是bootstrap title
    {% endblock %}
{% endblock %}