academic/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponseRedirect

urlpatterns = [
    url(r'^$', lambda r: HttpResponseRedirect('projects/index')),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls')),
]

projects/urls.py
from django.conf.urls import url, include
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import UpdateView

from django.contrib.auth import views
from projects.filters import ThesisInfoFilter, MeetingInfoFilter, NoticeFilter
from projects.form import ThesisInfoAddForm, MeetingInfoAddForm, NoticeAddForm
from .models import ThesisInfo, MeetingInfo,Notice
from .views import *

app_name = 'projects'

urlpatterns = [
    url(r'^login/$', login,
        {'template_name': 'projects/myuser/login.html'},name='userLogin'),
    url(r'^logout/$', views.logout, {'template_name': 'projects/myuser/login.html'}, name='logout'),

    url(r'^index$', indexView, name='index'),

    #thesisInfo
    url(r'^thesisInfoList$',
        ThesisInfoListView.as_view(model=ThesisInfo, filterset_class=ThesisInfoFilter, template_name='projects/thesisInfo/list.html',
                                 paginate_by=7),name='thesisInfoList'),
    url(r'^thesisInfoAdd$',add, name='thesisInfoAdd'),
    url(r'^thesisInfo/(?P<pk>[0-9]+)/$', DetailView.as_view(model=ThesisInfo, template_name='projects/thesisInfo/detail.html'),
        name='thesisInfoDetail'),
    url(r'^(?P<pk>[0-9]+)/updatethesisInfo$', UpdateView.as_view(model=ThesisInfo, form_class=ThesisInfoAddForm,
                                                                 template_name='projects/thesisInfo/update.html',
                                                                 success_url=reverse_lazy('projects:thesisInfoList')),
        name='thesisInfoUpdate'),
    url(r'^(?P<pk>[0-9]+)/updatethesisInfo$', UpdateView.as_view(model=ThesisInfo, form_class=ThesisInfoAddForm,
                                                                 template_name='projects/thesisInfo/update.html',
                                                                 success_url=reverse_lazy('projects:thesisInfoList')),
        name='thesisInfoReview'),
    url(r'^(?P<pk>[0-9]+)/updatethesisInfo$', UpdateView.as_view(model=ThesisInfo, form_class=ThesisInfoAddForm,
                                                                 template_name='projects/thesisInfo/update.html',
                                                                 success_url=reverse_lazy('projects:thesisInfoList')),
        name='thesisInfoCheck'),
    url(r'^(?P<pk>[0-9]+)/deletethesisInfo$',
        DeleteView.as_view(model=ThesisInfo, success_url=reverse_lazy('projects:thesisInfoList')), name='thesisInfoDelete'),
    #meetingInfo
    url(r'^meetingInfoList$',
        MeetingInfoListView.as_view(model=MeetingInfo, filterset_class=MeetingInfoFilter,
                                   template_name='projects/meetingInfo/list.html',
                                   paginate_by=7), name='meetingInfoList'),
    url(r'^meetingInfoAdd$',
        CreateView.as_view(model=MeetingInfo, template_name='projects/meetingInfo/add.html',
                           form_class=MeetingInfoAddForm,
                           success_url=reverse_lazy('projects:meetingInfoList')), name='meetingInfoAdd'),
    url(r'^meetingInfo/(?P<pk>[0-9]+)/$',
        DetailView.as_view(model=MeetingInfo, template_name='projects/meetingInfo/detail.html'),
        name='meetingInfoDetail'),
    url(r'^(?P<pk>[0-9]+)/updatemeetingInfo$', UpdateView.as_view(model=MeetingInfo, form_class=MeetingInfoAddForm,
                                                                 template_name='projects/meetingInfo/update.html',
                                                                 success_url=reverse_lazy('projects:meetingInfoList')),
        name='meetingInfoUpdate'),
    url(r'^(?P<pk>[0-9]+)/deletemeetingInfo$',
        DeleteView.as_view(model=MeetingInfo, success_url=reverse_lazy('projects:meetingInfoList')),
        name='meetingInfoDelete'),
    #notice
    url(r'^noticeList$',
        NoticeListView.as_view(model=Notice, filterset_class= NoticeFilter,
                                   template_name='projects/notice/list.html',
                                   paginate_by=7), name='noticeList'),
    url(r'^noticeAdd$',
        CreateView.as_view(model=Notice, template_name='projects/notice/add.html',
                           form_class=NoticeAddForm,
                           success_url=reverse_lazy('projects:noticeList')), name='noticeAdd'),
    url(r'^notice/(?P<pk>[0-9]+)/$',
        DetailView.as_view(model=Notice, template_name='projects/notice/detail.html'),
        name='meetingInfoDetail'),
    url(r'^(?P<pk>[0-9]+)/updatenotice$', UpdateView.as_view(model=Notice, form_class=NoticeAddForm,
                                                                 template_name='projects/notice/update.html',
                                                                 success_url=reverse_lazy('projects:noticeList')),
        name='noticeUpdate'),
    url(r'^(?P<pk>[0-9]+)/deletenotice$',
        DeleteView.as_view(model=Notice, success_url=reverse_lazy('projects:noticeList')),
        name='noticeDelete'),
]

projects/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.

class userInfo(models.Model):
    USER_TYPE = (
        (1,'管理员'),
        (2,'审稿员'),
        (3,'参会者')
    )
    type = models.IntegerField(verbose_name="用户类型",choices=USER_TYPE)
    user = models.OneToOneField(User)

class ThesisInfo(models.Model):
    STATUS = (
        (1,'通过'),
        (2,'不通过'),
    )
    theme = models.CharField(verbose_name="主题", max_length=100)
    headline = models.CharField(verbose_name="摘要", max_length=100)
    keyword = models.CharField(verbose_name="关键词", max_length=50)
    user = models.ForeignKey(User,verbose_name="用户")
    thesisUrl = models.FileField(verbose_name="论文上传", upload_to='projects/static/documents/%Y/%m/%d')
    auditStatus = models.IntegerField(verbose_name="审核状态", choices=STATUS,blank=True,null=True)
    reviewStatus = models.IntegerField(verbose_name="评审状态", choices=STATUS,blank=True,null=True)
    create_time = models.DateTimeField(verbose_name="创建时间",default='2017-4-23')
    modifyTime = models.DateTimeField(verbose_name="修改时间")

class MeetingInfo(models.Model):
    meeting_name = models.CharField(verbose_name="会议名称", max_length=100)
    start_time = models.DateTimeField(verbose_name="开始时间")
    end_time = models.DateTimeField(verbose_name="结束时间")
    meeting_address = models.CharField(verbose_name="会议地址", max_length=100)
    meeting_plan = models.CharField(verbose_name="会议安排", max_length=500)
    create_time = models.DateTimeField(verbose_name="创建时间",default='2017-4-23')
    create_user = models.ForeignKey(User,verbose_name="创建人")
    def __str__(self):
        return self.meeting_name

class Notice(models.Model):
    message = models.CharField(verbose_name="信息内容",max_length=1000)
    meetingInfo = models.ForeignKey(MeetingInfo,verbose_name="会议")
    create_time = models.DateTimeField(verbose_name="创建时间",default='2017-4-23')

projects/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth import views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template.response import TemplateResponse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django_filters.views import FilterView
from projects.form import ThesisInfoAddForm
from projects.models import ThesisInfo


@csrf_protect
@never_cache
def login(request, template_name='registration/login.html',
          redirect_field_name=REDIRECT_FIELD_NAME,
          authentication_form=AuthenticationForm,
          extra_context=None, redirect_authenticated_user=False):
    """
    Displays the login form and handles the login action.
    """
    redirect_to = request.POST.get(redirect_field_name, request.GET.get(redirect_field_name, ''))

    if redirect_authenticated_user and request.user.is_authenticated:
        #redirect_to = _get_login_redirect_url(request, redirect_to)
        if redirect_to == request.path:
            raise ValueError(
                "Redirection loop for authenticated user detected. Check that "
                "your LOGIN_REDIRECT_URL doesn't point to a login page."
            )
        return HttpResponseRedirect(redirect_to)
    elif request.method == "POST":
        form = authentication_form(request, data=request.POST)
        if form.is_valid():
            views.auth_login(request, form.get_user())
            return HttpResponseRedirect('/projects/index')
        else:
            form = authentication_form(request)
        current_site = get_current_site(request)

        context = {
            'form': form,
            redirect_field_name: redirect_to,
            'site': current_site,
            'site_name': current_site.name,
        }
        if extra_context is not None:
            context.update(extra_context)
        return TemplateResponse(request, template_name, context)


class ThesisInfoListView(FilterView):
    def get_queryset(self):
        if self.request.user.username == 'admin':
            query_set = ThesisInfo.objects.all()
        if self.request.user.username == 'wangkai1':
            query_set = ThesisInfo.objects.filter(user=self.request.user)
        else:
            query_set = ThesisInfo.objects.all()
        return query_set
    def get_paginate_by(self, queryset):
        return self.paginate_by

class NoticeListView(FilterView):
    def get_paginate_by(self, queryset):
        return self.paginate_by

class MeetingInfoListView(FilterView):
    def get_paginate_by(self, queryset):
        return self.paginate_by

@login_required
def indexView(request):
        return render(request, 'projects/index.html')

def add(request):
    template = 'projects/thesisInfo/add.html'
    if request.method == 'POST':
        form = ThesisInfoAddForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/projects/thesisInfoList')
    else:
        form = ThesisInfoAddForm()
    return render(request, template, {'form': form})

def upload(request):
    template = 'projects/thesisInfo/update.html'
    if request.method == 'POST':
        form = ThesisInfoAddForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/projects/thesisInfoList')
    else:
        form = ThesisInfoAddForm()
    return render(request, template, {'form': form})



        # @receiver(signals.post_init, sender=Notice)
# def project_init_signal(instance, sender, **kwargs):
#     instance.__noticeid = instance.pk
#     instance.__meetingInfo = instance.meetingInfo
#     instance.__message = instance.message
#
# @receiver(signals.post_save, sender=Notice)
# def notice_post_save(instance, created, raw, update_fields,sender, **kwargs):

projects/templates/projects/meetingInfo/add.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% block content %}
    <script>
        (
                jQuery(".datepicker").datepicker({
                format: "yyyy-mm-dd",
                language: 'zh-CN',
                autoclose: true,
                todayHighlight: true
            })
        )();
    </script>
    <div class="col-md-10">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">添加会议</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="">
                {% csrf_token %}
                <div class="box-body">
                    {% for field in form %}
                        <div class="form-group">
                            {% if field.field.required %}
                              <label class="col-sm-2 control-label">{{ field.label }}</label>
                            {% else %}
                              <label class="col-sm-2 control-label">{{ field.label }}(选填)</label>
                            {% endif %}
                            <div class="col-sm-8">
                                {% render_field field class+="form-control" %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <input class="btn btn-default" type="submit" value="保存">
                    <input class="btn btn-default" type="button" onclick="history.back();" value="返回">
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
    </div>
{% endblock %}

projects/templates/projects/meetingInfo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

projects/templates/projects/meetingInfo/list.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}会议管理{% endblock %}
{% block content %}
    <!-- 表格-->
    <div class="box">
        <div class="box-body">
        {% if request.user.username == 'admin' %}
            <a href="{% url 'projects:meetingInfoAdd'%}"><button type="button" class="btn btn-primary">添加会议</button></a>
        {% endif %}
            <table class="table table-bordered table-hover" style="margin-top:10px;">
                <thead>
                    <tr>
                        <th>会议名称</th>
                        <th>开始时间</th>
                        <th>结束时间</th>
                        <th>会议地址</th>
                        <th>会议安排</th>
                        <th>创建时间</th>
                        <th>创建人</th>
                        {% if request.user.username == 'admin' %}
                        <th>操作</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                {% for o in object_list %}
                    <tr>
                        <td>{{ o.meeting_name }}</td>
                        <td>{{ o.start_time|date:"Y年m月d日" }}</td>
                        <td>{{ o.end_time|date:"Y年m月d日" }}</td>
                        <td>{{ o.meeting_address }}</td>
                        <td>{{ o.meeting_plan }}</td>
                        <td>{{ o.create_time|date:"Y年m月d日" }}</td>
                        <td>{{ o.create_user }}</td>
                        {% if request.user.username == 'admin' %}
                        <td>
                        <div class="btn-group" >
                          <a class="btn btn-default" href="{% url 'projects:meetingInfoUpdate' pk=o.id %} "
                             style="margin-left:10px;">修改</a>
                            <form style="display:inline;" method="POST" action="{% url 'projects:meetingInfoDelete' pk=o.id %}">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-default " style="margin-left:10px;" value="删除"
                                   onclick="return confirm('确认删除这条记录吗？')">
                            </form>
                        </div>
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!-- /.box-body -->
    <div style="margin-left: 30px;">
        {% bootstrap_pagination page_obj %}
    </div>
    </div>
    <!-- /.box -->
{% endblock %}

projects/templates/projects/meetingInfo/update.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% load bootstrap3 %}
{% block content %}
    <script>
        jQuery(function () {
            jQuery(".select2").select2();
            jQuery(".datepicker").datepicker({
                dateFormat: "yy-mm-dd"
            });
        });
    </script>
    <!-- /.box -->
        <div class="col-md-10">
          <!-- Horizontal Form -->
          <div class="box box-info">
            <div class="box-header with-border">
              <h3 class="box-title">修改会议信息</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="post" action="">
                {% csrf_token %}
              <div class="box-body">
                  {% for field in form %}
                <div class="form-group">
                  <label class="col-sm-2 control-label">{{ field.label }}</label>
                  <div class="col-sm-8">
                      {% render_field field class+="form-control" %}
                  </div>
                </div>
                  {% endfor %}
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                    <input class="btn btn-default" type="submit" value="保存">
                    <input class="btn btn-default" type="button" onclick="history.back();" value="返回">
              </div>
              <!-- /.box-footer -->
            </form>
          </div>
        </div>
{% endblock %}